In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("data_resourse.csv")

In [3]:
dataset

,Scientific name,Common name,Species ID (TVK),Taxon Rank,Start date,Start date day,Start date month,Start date year,Latitude (WGS84),Longitude (WGS84),...,Survey key,Kingdom,Phylum,Class,Order,Family,Genus,Country,State/Province,Vitality
0,Capreolus capreolus,Roe Deer,NHMSYS0000080203,species,31/01/2018,31.0,1.0,2018.0,57.400200,-4.267900,...,iRecord | Mammals,Animalia,Chordata,Mammalia,Artiodactyla,Cervidae,Capreolus,United Kingdom,Scotland,NaN
1,Erinaceus europaeus,West European Hedgehog,NBNSYS0000005078,species,20/01/2021,20.0,1.0,2021.0,51.519214,-0.738969,...,iRecord | App,Animalia,Chordata,Mammalia,Insectivora,Erinaceidae,Erinaceus,United Kingdom,England,NaN
2,Halichoerus grypus,Grey Seal,NBNSYS0000005137,species,06/01/2016,6.0,1.0,2016.0,52.800000,1.600000,...,iRecord | Mammals,Animalia,Chordata,Mammalia,Carnivora,Phocidae,Halichoerus,United Kingdom,England,NaN
3,Talpa europaea,European Mole,NBNSYS0000005079,species,25/01/2017,25.0,1.0,2017.0,53.322473,-1.731987,...,iRecord | Import,Animalia,Chordata,Mammalia,Insectivora,Talpidae,Talpa,United Kingdom,England,NaN
4,Sciurus carolinensis,Eastern Grey Squirrel,NHMSYS0000332764,species,06/01/2016,6.0,1.0,2016.0,52.581700,-1.717600,...,iRecord | Mammals,Animalia,Chordata,Mammalia,Rodentia,Sciuridae,Sciurus,United Kingdom,England,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8703,Mustela nivalis,Weasel,NBNSYS0000005128,species,04/04/2015,4.0,4.0,2015.0,51.587927,-1.391558,...,Mammal Society | Mammal Atlas,Animalia,Chordata,Mammalia,Carnivora,Mustelidae,Mustela,United Kingdom,England,NaN
8704,Capreolus capreolus,Roe Deer,NHMSYS0000080203,species,05/04/2020,5.0,4.0,2020.0,52.082675,0.837207,...,iRecord | General data,Animalia,Chordata,Mammalia,Artiodactyla,Cervidae,Capreolus,United Kingdom,England,NaN
8705,Sciurus carolinensis,Eastern Grey Squirrel,NHMSYS0000332764,species,11/12/2020,11.0,12.0,2020.0,51.378738,-0.399375,...,iRecord | General data,Animalia,Chordata,Mammalia,Rodentia,Sciuridae,Sciurus,United Kingdom,England,NaN
8706,Sciurus carolinensis,Eastern Grey Squirrel,NHMSYS0000332764,species,22/12/2016,22.0,12.0,2016.0,55.023200,-1.609100,...,iRecord | Mammals,Animalia,Chordata,Mammalia,Rodentia,Sciuridae,Sciurus,United Kingdom,England,NaN
8707,Erinaceus europaeus,West,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
coloums_target = ["Taxon Rank", "Start date day", "Start date month", "Start date year"]
filtered_dataset = dataset[coloums_target].copy()
filtered_dataset

     Taxon Rank  Start date day  Start date month  Start date year
0       species            31.0               1.0           2018.0
1       species            20.0               1.0           2021.0
2       species             6.0               1.0           2016.0
3       species            25.0               1.0           2017.0
4       species             6.0               1.0           2016.0
...         ...             ...               ...              ...
8703    species             4.0               4.0           2015.0
8704    species             5.0               4.0           2020.0
8705    species            11.0              12.0           2020.0
8706    species            22.0              12.0           2016.0
8707        NaN             NaN               NaN              NaN

[8708 rows x 4 columns]

In [51]:
filtered_dataset["Taxon Rank"] = filtered_dataset["Taxon Rank"].replace({"species": 1, "family" : 2, "genus" : 3, "species hybrid" : 4})
filtered_dataset.dropna(inplace=True)
filtered_dataset.reset_index(drop=True, inplace=True)

In [53]:
filtered_dataset

     Taxon Rank  Start date day  Start date month  Start date year
0             1            31.0               1.0           2018.0
1             1            20.0               1.0           2021.0
2             1             6.0               1.0           2016.0
3             1            25.0               1.0           2017.0
4             1             6.0               1.0           2016.0
...         ...             ...               ...              ...
8702          1             4.0               4.0           2016.0
8703          1             4.0               4.0           2015.0
8704          1             5.0               4.0           2020.0
8705          1            11.0              12.0           2020.0
8706          1            22.0              12.0           2016.0

[8707 rows x 4 columns]

In [54]:
filtered_dataset.to_csv("filtered_dataset.csv")